DROP TABLE IF EXISTS `{prefix}content_1`;
DROP TABLE IF EXISTS `{prefix}content_1_verify`;
DROP TABLE IF EXISTS `{prefix}content_1_extend`;
DROP TABLE IF EXISTS `{prefix}search`;
DROP TABLE IF EXISTS `{prefix}category`;
DROP TABLE IF EXISTS `{prefix}favorite`;
DROP TABLE IF EXISTS `{prefix}model`;
DROP TABLE IF EXISTS `{prefix}model_field`;
DELETE FROM `{pre}menu` WHERE `namespace` = '{namespace}';
DELETE FROM `{pre}menu_data` WHERE `namespace` = '{namespace}';