<?php
if (!defined('IN_FINECMS')) exit();

/**
 * 用户权限配置信息
 */
return array (
  1 => 
  array (
    0 => 'index',
    1 => 'auth',
    2 => 'category',
    3 => 'content',
    4 => 'model',
    5 => 'user',
    6 => 'position',
    7 => 'linkage',
    8 => 'plugin',
    9 => 'attachment',
    10 => 'relatedlink',
    11 => 'block',
    12 => 'member',
    13 => 'theme',
    14 => 'html',
    15 => 'form',
    16 => 'tag',
    17 => 'ip',
    18 => 'site',
    19 => 'navbar',
    20 => 'menu',
  ),
  2 => 
  array (
    0 => '2-xitongshezhi-index',
    1 => 'index-config',
    2 => 'index-log',
    3 => 'index-attack',
    4 => 'ip-index',
    5 => 'menu-index',
    6 => '2-mobanguanli-index',
    7 => 'theme-index',
    8 => 'theme-demo',
    9 => 'theme-cache',
    10 => '2-shengchengjingtai-index',
    11 => 'html-index',
    12 => 'html-clear',
    13 => 'index-cache',
    14 => 'index-updatemap',
    15 => 'content-updateurl',
    16 => '2-guanliyuanshezhi-index',
    17 => 'user-add',
    18 => 'user-index',
    19 => 'auth-index',
    20 => 'auth-cache',
    21 => '3-lanmumoxing-index',
    22 => 'category-index',
    23 => 'attachment-index',
    24 => 'model-index',
    25 => '3-neirongxiangguan-index',
    26 => 'navbar-index',
    27 => 'block-index',
    28 => 'position-index',
    29 => 'tag-index',
    30 => 'relatedlink-index',
    31 => 'linkage-index',
    32 => '4-huiyuanguanli-index',
    33 => 'member-index',
    34 => 'member-pms',
    35 => 'member-group',
    36 => '4-huiyuanpeizhi-index',
    37 => 'member-confg',
    38 => '5-chajianliebiao-index',
    39 => 'plugin-index',
  ),
  3 => 
  array (
    0 => 'index-config',
    1 => 'auth-add',
    2 => 'auth-edit',
    3 => 'auth-set',
    4 => 'form-list',
  ),
);